### ISSUE TITLE
能否修改默认的配置文件

### ISSUE THREAD

**Issue by xiaotupansy** [liuhaoyang/butterfly#33]
"ServerAddress"从“http://localhost:9618“改成"http://+:9618"。
另外会否考虑支持一个官方的docker镜像？

**Comment by liuhaoyang** [comment]
加入待支持列表

**Comment by xiaotupansy** [comment]
另：
今天按照你的文档试了下，0.0.8版本跑不通。
没有任何追踪数据。

使用的命令如下
dotnet Butterfly.Web.dll --EnableHttpCollector=true --Storage=elasticsearch --ElasticSearchHosts=http://192.168.1.249:9200

es是基于docker的5.3版本，elasticsearch:5.3 

新建了一个.net core mvc项目，命令如下：
services.AddButterfly(option =>
            {
                option.CollectorUrl = Configuration["ButterflyAddr"];
                option.Service = "demo";
            });

**Comment by liuhaoyang** [comment]
这是一个bug  https://github.com/ButterflyAPM/butterfly-csharp/issues/31

**Comment by xiaotupansy** [comment]
我用0.0.7版本
发现es 5.3版本工作有问题
在5.6.8工作正常

**Comment by liuhaoyang** [comment]
@xiaotupansy 使用的ES Client驱动是6.0 可能是不支持旧的es版本 [Butterfly.Elasticsearch.csproj](https://github.com/ButterflyAPM/butterfly/blob/master/src/Butterfly.Elasticsearch/Butterfly.Elasticsearch.csproj#L24)

**Comment by xiaotupansy** [comment]
那建议写文档的时候标注一下，方便大家使用。
